Return an intersection type when nameMock is used
phpstan/phpstan-mockery pull request #19
Opened 2020-07-03 14:28 UTC by martinssipenko

This will return intersetion type when [`namedMock`](http://docs.mockery.io/en/latest/reference/creating_test_doubles.html#named-mocks) function is used.

2020-07-03 14:46 UTC, ondrejmirtes commented
Hi, this isn't sufficient as the extension will try to make a type from the first argument too.

2020-07-03 14:47 UTC, martinssipenko commented
> Hi, this isn't sufficient as the extension will try to make a type from the first argument too.

Hm, I understand first argument also represents a type, essantually `mockNamed('Foo', 'Bar')` is same as `calss Foo implements Bar`.

2020-07-03 14:51 UTC, ondrejmirtes commented
From the documentation I don't understand what the method does: http://docs.mockery.io/en/latest/cookbook/class_constants.html

There are only classes involved, and in PHP you can't create intersection types from classes.

2020-07-03 14:57 UTC, martinssipenko commented
When you mock something with `Mockery::mock(SomeInterface::class)` mockery creates a "fake" class that implements `SomeInterface` and a mock object from this "fake" class is created.

Now suppose you need to create two mock objects of same interface.
```
$mock1 = Mockery::mock(SomeInterface::class);
$mock2 = Mockery::mock(SomeInterface::class);
```

If you do `get_class($mock1)` and `get_class($mock2)` you will get the same result because the same "fake" class is used.

Using `namedMock` method you can get specify the name of the "fake" calss mockery creates, thus it allows to have two distinct objects that are created from different classes, but implement same interface.

2020-07-03 15:00 UTC, ondrejmirtes commented
Yeah but if class name in the first argument isn't an existing one, we have to skip it when creating the intersection...

2020-07-03 15:07 UTC, martinssipenko commented
Can you help me understand why? If we use `mock` method, then class/interface name (1st arg) can also be non-existant.

How do you think we can fix this?

2020-07-03 15:12 UTC, ondrejmirtes commented
> then class/interface name (1st arg) can also be non-existant.

I don't think that's true.

2020-07-03 15:14 UTC, martinssipenko commented
```php
<?php
// x.php

require_once __DIR__ . '/vendor/autoload.php';

$mock1 = Mockery::mock('WhaterverRandomNameIComeUpWith');
$mock2 = Mockery::mock('WhaterverRandomNameIComeUpWith');

var_dump(get_class($mock1));
var_dump(get_class($mock2));
```

```shell
php x.php 
/Users/msipenko/src/msipenko/forks/phpstan-mockery/x.php:8:
string(41) "Mockery_0__WhaterverRandomNameIComeUpWith"
/Users/msipenko/src/msipenko/forks/phpstan-mockery/x.php:9:
string(41) "Mockery_0__WhaterverRandomNameIComeUpWith"
```

2020-07-03 15:16 UTC, ondrejmirtes commented
Yeah but PHPStan won't like it: https://phpstan.org/r/31d8e42c-5d2c-420a-b7d0-8161f271e686

Is it a valid use-case?

2020-07-03 15:21 UTC, martinssipenko commented
Ah ok, I understand now, strangely I edited the code locally in my projects vendor directory, and just adding that entry to array  made PHPStan error go away.

Either way, what do you suggest we can do here?

2020-07-03 15:24 UTC, ondrejmirtes commented
There has to be another extension similar to MockDynamicReturnTypeExtension but that skips the first parameter.

2020-07-03 15:25 UTC, martinssipenko commented
Meybe we can just add something like this?

```php
if ($methodReflection->getName() === 'namedMock') {
			array_shift($methodCall->args);
		}
```

2020-07-03 15:36 UTC, ondrejmirtes commented
Nope, it'd be a mess, this needs a separate class.

2020-07-03 17:36 UTC, ondrejmirtes requested changes
Some code added to https://github.com/phpstan/phpstan-mockery/blob/master/tests/Mockery/MockeryTest.php to verify by running `vendor/bin/phing phpstan` this actually works would be nice.

2020-07-03 17:36 UTC, ondrejmirtes commented on src/Mockery/Type/MockDynamicNamedMockReturnTypeExtension.php
> +		array_shift($args);
You need to make sure the array has at least two elements.

2020-07-21 06:44 UTC, martinssipenko commented
@ondrejmirtes, any updates on this?

2020-07-21 09:15 UTC, merged

2020-07-21 09:16 UTC, ondrejmirtes commented
Merged and released, thanks.

2020-07-21 09:47 UTC, martinssipenko commented
Thank you!